name:                vcompose
version:             0.1.0.0
github:              "githubuser/vcompose"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- DeriveGeneric

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vcompose#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- directory
- errors
- filepath
- split
- text
- transformers
- unordered-containers
- vector
- yaml

library:
  source-dirs: src

executables:
  vcompose-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vcompose

tests:
  vcompose-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vcompose
